version: "3.7"
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - gm-net
  gm-stories:
    build:
      context: ./GioiMon-Stories
      dockerfile: Dockerfile
    ports:
      - 8803:8803
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.c3goi4eyoa0r.ap-southeast-2.rds.amazonaws.com/gm_stories
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ZkMErAor36cJsjMEXFR9
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - gm-net
    depends_on:
      - eureka-server
  gm-user:
    build:
      context: ./gm_user
      dockerfile: Dockerfile
    ports:
      - 8801:8801
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.c3goi4eyoa0r.ap-southeast-2.rds.amazonaws.com/gm_users
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: ZkMErAor36cJsjMEXFR9
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - gm-net
    depends_on:
      - eureka-server
  gm_gateway:
    build:
      context: ./gm_gateway
      dockerfile: Dockerfile
    ports:
      - 10440:10440
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      USER_ID: gm-user
      USER_URI: lb://gm-user
      STORY_ID: gm-stories
      STORY_URI: lb://gm-stories
    networks:
      - gm-net
    depends_on:
      - eureka-server
      - gm-user
      - gm-stories
networks:
  gm-net:
    name: gm-network
volumes:
  data:
