version: "3.7"
services:
  eureka-server:
    image: openjdk:17-jdk-slim
    container_name: eureka-server
    volumes:
      - ./eureka-server/target:/var/app/gm
    ports:
      - "8761:8761"
      - "7761:7761"
    networks:
      - gm-net
    working_dir: /var/app/gm
    entrypoint:
      - java
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7761"
      - -jar
      - eureka-server-0.0.1-SNAPSHOT.jar
  gm-story:
    image: openjdk:17-jdk-slim
    container_name: gm-story
    volumes:
      - ./gm-story/target:/var/app/gm
    ports:
      - "8803:8803"
      - "7803:7803"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://54.153.185.93:3306/gm_stories
      SPRING_DATASOURCE_USERNAME: gm
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EUREKA_URI: http://eureka-server:8761/eureka
    entrypoint:
      - java
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7803"
      - -jar
      - gm-story-0.0.1-SNAPSHOT.jar
    networks:
      - gm-net
    working_dir: /var/app/gm
    depends_on:
      - eureka-server
  gm-user:
    image: openjdk:17-jdk-slim
    volumes:
      - ./gm-user/target:/var/app/gm
    container_name: gm-user
    ports:
      - "8801:8801"
      - "7801:7801"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://54.153.185.93:3306/gm_users
      SPRING_DATASOURCE_USERNAME: gm
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - gm-net
    working_dir: /var/app/gm
    depends_on:
      - eureka-server
    entrypoint:
      - java
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7801"
      - -jar
      - gm-user-0.0.1-SNAPSHOT.jar
  gm-post:
    image: openjdk:17-jdk-slim
    container_name: gm-post
    volumes:
      - ./gm-post/target:/var/app/gm
    ports:
      - "8802:8802"
      - "7802:7802"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://54.153.185.93:3306/gm_post
      SPRING_DATASOURCE_USERNAME: gm
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - gm-net
    working_dir: /var/app/gm
    depends_on:
      - eureka-server
      - gm-story
      - gm-user
    entrypoint:
      - java
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:7802"
      - -jar
      - gm-post-0.0.1-SNAPSHOT.jar
  gm_gateway:
    image: openjdk:17-jdk-slim
    container_name: gm-gateway
    volumes:
      - ./gm-gateway/target:/var/app/gm
    ports:
      - "10440:10440"
      - "9440:9440"
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      USER_ID: gm-user
      USER_URI: lb://gm-user
      STORY_ID: gm-story
      STORY_URI: lb://gm-story
      POST_ID: gm-post
      POST_URI: lb://gm-post
    networks:
      - gm-net
    working_dir: /var/app/gm
    depends_on:
      - eureka-server
      - gm-user
      - gm-story
      - gm-post
    entrypoint:
      - java
      - "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9440"
      - -jar
      - gm-gateway-0.0.1-SNAPSHOT.jar
networks:
  gm-net:
    name: gm-network
volumes:
  data:
