version: "3.7"
services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    networks:
      - gm-net
  gm-stories:
    build:
      context: ./gioimon-stories
      dockerfile: Dockerfile
    ports:
      - "8803:8803"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://54.153.185.93:3306/gm_stories
      SPRING_DATASOURCE_USERNAME: gm
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - gm-net
    depends_on:
      - eureka-server
  gm-user:
    build:
      context: ./gm_user
      dockerfile: Dockerfile
    ports:
      - "8801:8801"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://54.153.185.93:3306/gm_users
      SPRING_DATASOURCE_USERNAME: gm
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - gm-net
    depends_on:
      - eureka-server
  gm-post:
    build:
      context: ./gm_post
      dockerfile: Dockerfile
    ports:
      - "8802:8802"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://54.153.185.93:3306/gm_post
      SPRING_DATASOURCE_USERNAME: gm
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      EUREKA_URI: http://eureka-server:8761/eureka
    networks:
      - gm-net
    depends_on:
      - eureka-server
      - gm-stories
      - gm-user
  gm_gateway:
    build:
      context: ./gm_gateway
      dockerfile: Dockerfile
    ports:
      - 10440:10440
    environment:
      EUREKA_URI: http://eureka-server:8761/eureka
      USER_ID: gm-user
      USER_URI: lb://gm-user
      STORY_ID: gm-stories
      STORY_URI: lb://gm-stories
    networks:
      - gm-net
    depends_on:
      - eureka-server
      - gm-user
      - gm-stories
networks:
  gm-net:
    name: gm-network
volumes:
  data:
