server:
  port: 10440

spring.application.name: gm_gateway
spring.cloud.discovery.enabled: true

spring.cloud.gateway.discovery.locator.enabled: true
spring.cloud.gateway.discovery.locator.lowerCaseServiceId: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

application:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:*}
    allowed-methods: ${ALLOWED_METHODS:*}
    allowed-headers: ${ALLOWED_HEADERS:*}
gateway:
  allowed:
    hosts: "*"
spring.cloud.gateway:
  default-filters:
    - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  httpclient:
    connect-timeout: 10000
    response-timeout: 60s
  globalcors:
    cors-configurations:
      "[/**]":
        allowedOrigins: "*"
        allowedHeaders: "*"
        allowedMethods:
          - GET
          - POST
          - DELETE
          - PUT
          - OPTIONS
  routes:
    - id: ${ADMIN_ID:gm-administrator}
      uri: ${ADMIN_URI:http://localhost:8801}
      predicates:
        - Path=/admin/**
      filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - AddResponseHeader=appId,${gateway.for.app.code}
        - StripPrefix=1
    - id: ${STORY_ID:gm-stories}
      uri: ${STORY_URI:http://localhost:8803}
      predicates:
        - Path=/story/**
      filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin
        - StripPrefix=1
